### ISSUE TITLE
ExportBatchDVHs

### ISSUE THREAD

**Issue by kerlannlc** [VarianAPIs/samples#1]
Hello,

I've tried the Eclipse script "ExportBatchDVHs" on our system (TBox: Windows 7 64-bit, VARIAN v11.0 and Microsoft Visual Studio Express 2012) and I have a recurrent error:

> A database operation failed and needs to be retried.
> (Press 'Cancel' to abord the application)
> ReadDoseFailed: Cannot open pixel file '\\VMSTBOX\VA_DATA$\Patients\X\DoseVolumes\Y'

(X is the patient id and Y, the name of the image)

I have therefore checked the path but unfortunately, not even 40 folders were in the Patients folder and all last modified in 2014.
I’ve tried to run other examples provided (Example_Patients) but the same message error comes up. And I’m only interested in standalone applications so I haven’t tried other applications where the UserHome context is used.

I tried other scripts and everything worked so there is no issue with the program but with the database or TBox itself.

Many thanks for your help!

(Happy to provide my code although, it is this [one](https://github.com/VarianAPIs/samples/tree/master/Eclipse%20Scripting%20API/projects/ExportBatchDVHs).)

**Comment by wkeranen** [comment]
Hi,
As mentioned in a direct email, we think the problem is that the bulk file data (images, doses, and more) did not get copied over when the T-box was built.

The only fix is to copy the files from the original image file server “VA_DATA$\filedata” share where the T-box database came from to the T-box image file server VA_DATA$ share.
